import type { Chunk } from "@/lib/types";

/**
 * Curated knowledge base for Kwu Tung North. Every chunk is a close paraphrase
 * of the cited source; figures are copied verbatim from that source.
 */
export const CHUNKS: Chunk[] = [
  // ── Transport ────────────────────────────────────────────────────────────
  {
    id: "ktu-erl-station",
    sourceId: "hyd-nol",
    heading: "Kwu Tung Station on the East Rail Line",
    headingZh: "東鐵綫古洞站",
    text: "Kwu Tung Station is an intermediate station between Sheung Shui Station and Lok Ma Chau Station on the Lok Ma Chau Spur Line, and will connect to the Northern Link Main Line. Construction commenced in 2023 and the station is expected to come into operation in 2027 as scheduled.",
    textZh: "古洞站是落馬洲支綫上水站與落馬洲站之間的中途站，並將連接北環綫主綫。工程於2023年展開，預計於2027年如期投入服務。",
    topics: ["transport", "crossborder"],
    status: "under_construction",
    placeIds: ["ktu-station", "erl-spur", "sheung-shui"],
    timeline: "2027",
  },
  {
    id: "ktu-topout",
    sourceId: "mtr-topout",
    heading: "Station topped out; shorter rail journey to Sheung Shui",
    headingZh: "古洞站平頂；往上水的鐵路車程將大幅縮短",
    text: "A topping-out ceremony on 19 November 2025 marked the substantial completion of civil works at Kwu Tung Station on the East Rail Line; the project has entered the electrical and mechanical works stage and is targeted for completion in 2027. MTR states that, compared with existing public transport options, journey time between the Kwu Tung North NDA and Sheung Shui by rail will be substantially shortened.",
    textZh: "東鐵綫古洞站於2025年11月19日舉行平頂儀式，標誌土木工程大致完成，工程已進入機電階段，目標2027年完成。港鐵表示，與現有公共交通相比，古洞北新發展區往返上水的鐵路車程將大幅縮短。",
    topics: ["transport"],
    status: "under_construction",
    placeIds: ["ktu-station"],
    timeline: "2027",
  },
  {
    id: "ktu-location",
    sourceId: "mtr-ktu",
    heading: "Station sits in the future Town Centre",
    headingZh: "車站位於未來市中心",
    text: "The proposed Kwu Tung Station is located at the junction of the existing Ma Tso Lung Road and Ho Sheung Heung Road, which is also the town centre of the future Kwu Tung North NDA, near the NDA's residential, retail, leisure, social services and community facilities. Kwu Tung Station on the East Rail Line and Kwu Tung Station on the Northern Link will be next to each other and inter-connected, so passengers can interchange between the two lines.",
    textZh: "擬建古洞站位於現有馬草壟路與河上鄉路交界，即未來古洞北新發展區市中心，鄰近住宅、零售、休閒、社會服務及社區設施。東鐵綫古洞站與北環綫古洞站將相鄰並互相連接，方便乘客轉乘。",
    topics: ["transport", "community", "accessibility"],
    status: "under_construction",
    placeIds: ["ktu-station", "town-centre"],
  },
  {
    id: "nol-main-line",
    sourceId: "hyd-nol",
    heading: "Northern Link Main Line",
    headingZh: "北環綫主綫",
    text: "The Northern Link Main Line is a railway of about 10.7 km connecting Kam Sheung Road Station and Kwu Tung Station, with three intermediate stations at San Tin, Ngau Tam Mei and Au Tau. Construction commenced in 2025 for commissioning by 2034 or earlier.",
    textZh: "北環綫主綫全長約10.7公里，連接錦上路站與古洞站，設有新田、牛潭尾及凹頭三個中途站。工程於2025年展開，目標2034年或之前通車。",
    topics: ["transport", "employment"],
    status: "under_construction",
    placeIds: ["nol-main", "ktu-station"],
    timeline: "by 2034",
  },
  {
    id: "nol-journey-time",
    sourceId: "isd-nol-scheme",
    heading: "Expected journey time to Kam Sheung Road",
    headingZh: "往錦上路的預計車程",
    text: "When the Northern Link Main Line comes into operation, travel time between Kam Sheung Road Station and Kwu Tung Station is expected to be substantially reduced from the current 60 to 80 minutes during peak hours to about 12 minutes. The Main Line will connect the Tuen Ma Line and East Rail Line, forming a railway loop linking the New Territories and the Kowloon urban area.",
    textZh: "北環綫主綫通車後，錦上路站至古洞站的繁忙時間車程預計由現時60至80分鐘大幅縮短至約12分鐘。主綫將連接屯馬綫與東鐵綫，形成連接新界與九龍市區的鐵路環綫。",
    topics: ["transport", "employment"],
    status: "under_construction",
    placeIds: ["nol-main"],
    timeline: "by 2034",
  },
  {
    id: "nol-phasing",
    sourceId: "mtr-nol-explained",
    heading: "How the Northern Link is being delivered in parts",
    headingZh: "北環綫分部分推展",
    text: "Part 1 of the Project Agreement covers construction of Kwu Tung, Au Tau and Kam Sheung Road stations and the tunnel sections from Kwu Tung to San Tin and Au Tau to Kam Sheung Road. San Tin and Ngau Tam Mei stations, the remaining Main Line works and the depot integrated with the Spur Line will be addressed in a Part 2 Project Agreement, with the aim of commissioning the Main Line and Spur Line together no later than 2034.",
    textZh: "項目協議第一部分涵蓋古洞、凹頭及錦上路站，以及古洞至新田、凹頭至錦上路的隧道段。新田站、牛潭尾站、主綫其餘工程及與支綫整合的車廠將於第二部分項目協議處理，目標主綫及支綫於2034年或之前同步通車。",
    topics: ["transport"],
    status: "proposed",
    placeIds: ["nol-main"],
    timeline: "no later than 2034",
  },
  {
    id: "roads",
    sourceId: "cedd-ktnfln",
    heading: "Road improvements",
    headingZh: "道路改善工程",
    text: "The Fanling Bypass (Eastern Section) serving Fanling North was completed and commissioned in May 2026. Widening of Fanling Highway (Kwu Tung Section), the Fanling Bypass Western Section and a flyover along Po Shek Wu Road to Fanling Highway (westbound) will be carried out under the Remaining Phase for completion in 2031.",
    textZh: "服務粉嶺北的粉嶺繞道（東段）已於2026年5月落成啟用。粉嶺公路（古洞段）擴闊、粉嶺繞道西段及寶石湖路往粉嶺公路（西行）的天橋將於餘下階段進行，目標2031年完成。",
    topics: ["transport"],
    status: "planned",
    placeIds: [],
    timeline: "2031",
  },

  // ── Walkability & accessibility ──────────────────────────────────────────
  {
    id: "odp-500m",
    sourceId: "pland-odp",
    heading: "Most homes planned within 500 m of the station",
    headingZh: "大部分住宅規劃於車站500米範圍內",
    text: "High density residential developments, workplaces, leisure and public service facilities are concentrated within the 500 m catchments of the proposed railway station and public transport interchange in the Town Centre, to offer the majority of future residents convenient access to public transport. Subsidised housing sites in Areas 19, 21 and 24 (Town Centre) and Areas 12 and 13 (North Residential Area) are all located within 500 m walking distance of the proposed railway station.",
    textZh: "高密度住宅、工作地點、休閒及公共服務設施集中於市中心擬建鐵路站及公共運輸交匯處的500米範圍內，讓大部分未來居民方便使用公共交通。第19、21、24區（市中心）及第12、13區（北部住宅區）的資助房屋用地均位於擬建鐵路站500米步行距離內。",
    topics: ["accessibility", "transport", "housing"],
    status: "planned",
    placeIds: ["area-19-housing", "north-residential", "ktu-station"],
  },
  {
    id: "odp-footbridges",
    sourceId: "pland-odp",
    heading: "Footbridges to existing communities",
    headingZh: "連接現有社區的行人天橋",
    text: "Pedestrian linkages in the form of footbridges to Kwu Tung South across the Fanling Highway, and footbridges to Ho Sheung Heung and Yin Kong, are proposed to provide easy access for pedestrians between these areas and the Town Centre. A multi-level pedestrian connection integrating elevated and at-grade routes is planned to connect the public transport interchange.",
    textZh: "規劃建議興建橫跨粉嶺公路往古洞南的行人天橋，以及往河上鄉和燕崗的行人天橋，方便行人往返市中心。另規劃結合高架及地面的多層行人連接系統，連接公共運輸交匯處。",
    topics: ["accessibility", "transport", "elderly"],
    status: "proposed",
    placeIds: ["footbridges-kts", "town-centre"],
  },
  {
    id: "odp-pedestrian-env",
    sourceId: "pland-odp",
    heading: "Car-free Town Centre and continuous footpaths",
    headingZh: "無車市中心及連貫行人路",
    text: "Footpaths will be pedestrian friendly, continuous and landscaped. The Town Centre would be pedestrianised to provide a motor vehicle-free walking environment by placing vehicular roads away from it, with a cruciform pedestrian shopping street. Cycle tracks run along open space spines and riverside promenades, with cycle parking proposed close to the railway station and public transport interchange.",
    textZh: "行人路將以行人友善、連貫及綠化為原則。市中心將行人化，車路遠離市中心，營造無車步行環境，並設十字形行人購物街。單車徑沿休憩空間主軸及河畔長廊設置，鐵路站及公共運輸交匯處附近亦建議設單車停泊處。",
    topics: ["accessibility", "green", "transport"],
    status: "planned",
    placeIds: ["town-centre"],
  },

  // ── Community & elderly facilities ───────────────────────────────────────
  {
    id: "civic-hub",
    sourceId: "pland-odp",
    heading: "Area 29 civic hub",
    headingZh: "第29區社區樞紐",
    text: "A site in Area 29 is reserved for a district library, a sports centre, a community hall, a post office, some social welfare facilities and other government facilities. With good access to the proposed railway station, the public transport interchange and connections to Kwu Tung South, it will serve as a hub of civic activities and social services. The land to its west abutting Road D1 is planned for the Multi-welfare Services Complex.",
    textZh: "第29區用地預留作地區圖書館、體育館、社區會堂、郵政局、部分社會福利設施及其他政府設施。該處鄰近擬建鐵路站、公共運輸交匯處並連接古洞南，將成為公民活動及社會服務樞紐。其西面毗鄰D1路的土地規劃作多福利服務綜合大樓。",
    topics: ["community", "elderly"],
    status: "planned",
    placeIds: ["area-29-civic", "mwsc"],
  },
  {
    id: "mwsc-detail",
    sourceId: "devb-1497",
    heading: "Multi-welfare Services Complex",
    headingZh: "多福利服務綜合大樓",
    text: "The Multi-welfare Services Complex in Kwu Tung North will provide Day Care Units for the Elderly and about 1,750 places for the elderly, plus a Day Activity Centre cum Hostel for Severely Mentally Handicapped Persons and a Care and Attention Home for Severely Disabled Persons. It will also reprovision eligible elderly residents of existing residential care homes at Dills Corner Garden affected by the NDA. Because it sits beside Fanling Highway, it uses an H-shaped layout and architectural fins to shield traffic noise.",
    textZh: "古洞北多福利服務綜合大樓將提供長者日間護理單位及約1,750個長者宿位，另設嚴重弱智人士日間活動中心暨宿舍及嚴重殘疾人士護理院，並安置受新發展區影響的得利歷花園現有安老院舍合資格長者。由於毗鄰粉嶺公路，大樓採用H形設計及建築鰭片以阻隔交通噪音。",
    topics: ["elderly", "community", "healthcare", "accessibility"],
    status: "planned",
    placeIds: ["mwsc"],
  },
  {
    id: "area19-facilities",
    sourceId: "devb-467",
    heading: "Facilities next to the Area 19 public housing",
    headingZh: "第19區公營房屋旁的設施",
    text: "Next to the public housing site in Area 19 will be a public market, a Multi-welfare Services Complex of the Social Welfare Department, schools, a sports centre, a library, a community centre, public transport interchanges and the future Kwu Tung Station on the Northern Link.",
    textZh: "第19區公營房屋用地旁將設有公眾街市、社會福利署多福利服務綜合大樓、學校、體育館、圖書館、社區中心、公共運輸交匯處及未來北環綫古洞站。",
    topics: ["community", "elderly", "education", "transport"],
    status: "planned",
    placeIds: ["area-19-housing", "mwsc", "town-centre"],
  },
  {
    id: "town-centre-elderly",
    sourceId: "pland-odp",
    heading: "Kindergartens and a district elderly centre in the Town Centre",
    headingZh: "市中心的幼稚園及長者地區中心",
    text: "Social and community facilities proposed within the two Town Centre sites beside the Town Plaza include a nursery and kindergarten in the western site, and a nursery and kindergarten and a District Elderly Community Centre in the eastern site.",
    textZh: "市鎮廣場旁兩幅市中心用地內建議設置社區設施，包括西面用地的幼兒園暨幼稚園，以及東面用地的幼兒園暨幼稚園和長者地區中心。",
    topics: ["elderly", "education", "community"],
    status: "planned",
    placeIds: ["town-centre"],
  },
  {
    id: "schools",
    sourceId: "pland-odp",
    heading: "Schools",
    headingZh: "學校",
    text: "The Kwu Tung North ODP proposes primary and secondary schools within the NDA, including sites in the North Residential Area, planned according to the Hong Kong Planning Standards and Guidelines.",
    textZh: "古洞北分區計劃大綱圖建議在新發展區內設置中小學，包括北部住宅區的用地，並按《香港規劃標準與準則》規劃。",
    topics: ["education", "community"],
    status: "planned",
    placeIds: ["north-residential"],
  },

  // ── Healthcare ───────────────────────────────────────────────────────────
  {
    id: "hospital-superseded",
    sourceId: "legco-lcq17",
    heading: "Kwu Tung North hospital replaced by Ngau Tam Mei plan",
    headingZh: "古洞北醫院方案由牛潭尾計劃取代",
    text: "Because the site reserved for healthcare facilities in the Kwu Tung North NDA is relatively small with constraints on expansion, the Government plans to replace the previously proposed new hospital at Kwu Tung North with a new integrated medical teaching and research hospital at Ngau Tam Mei, on a site of about nine hectares with about 3,000 beds. Details and implementation schedules are being studied under the review of the Second Hospital Development Plan.",
    textZh: "由於古洞北新發展區預留的醫療設施用地面積較小且擴展受限，政府計劃以牛潭尾一所新的綜合醫學教學及研究醫院（用地約九公頃、約3,000張病床）取代原先建議的古洞北新醫院。相關細節及推展時間表正於第二個醫院發展計劃檢討中研究。",
    topics: ["healthcare", "elderly"],
    status: "superseded",
    placeIds: ["area-28-health", "ntm-hospital"],
  },
  {
    id: "ndh-expansion",
    sourceId: "legco-lcq17",
    heading: "North District Hospital expansion",
    headingZh: "北區醫院擴建",
    text: "Main works of the North District Hospital expansion commenced in September 2024, aiming to complete the new acute block in 2028 for gradual commissioning of services starting from 2029.",
    textZh: "北區醫院擴建主體工程已於2024年9月展開，目標於2028年完成新急症大樓，並由2029年起逐步投入服務。",
    topics: ["healthcare", "elderly"],
    status: "under_construction",
    placeIds: ["ndh"],
    timeline: "2028–2029",
  },
  {
    id: "odp-area28",
    sourceId: "pland-odp",
    heading: "Area 28 healthcare reservation on the plan",
    headingZh: "大綱圖上的第28區醫療用地",
    text: "The draft ODP still shows a site in the south-western part of the NDA (Area 28) reserved for a proposed hospital, polyclinic and general clinic/health centre to serve the KTN/FLN NDA, the wider population and nearby residents.",
    textZh: "草圖仍顯示新發展區西南部（第28區）預留作擬建醫院、普通科診所及健康中心，服務古洞北／粉嶺北新發展區及附近居民。",
    topics: ["healthcare"],
    status: "under_review",
    placeIds: ["area-28-health"],
  },

  // ── Green space & environment ────────────────────────────────────────────
  {
    id: "lvnp",
    sourceId: "lvnp",
    heading: "Long Valley Nature Park",
    headingZh: "塱原自然公園",
    text: "Long Valley Nature Park is about 37 ha, divided into a Visitor Zone (5 ha), Agriculture Zone (11 ha) and Biodiversity Zone (21 ha). It was developed as a mitigation for the ecological impact of the Kwu Tung North and Fanling North NDAs, with construction starting in late 2019, and opened in November 2024.",
    textZh: "塱原自然公園佔地約37公頃，分為訪客區（5公頃）、農業區（11公頃）及生物多樣性區（21公頃），作為古洞北及粉嶺北新發展區生態影響的緩解措施，於2019年底動工，2024年11月開放。",
    topics: ["green", "environment"],
    status: "completed",
    placeIds: ["long-valley"],
  },
  {
    id: "lvnp-access",
    sourceId: "afcd-lvnp",
    heading: "Getting to Long Valley Nature Park today",
    headingZh: "現時前往塱原自然公園",
    text: "AFCD lists walking distances from public transport of about 700 m from the red minibus 17 stop and about 980 m from the bus 76K stop. There are 30 private car parking spaces including 1 designated space for people with disabilities, and visitors are encouraged to use public transport.",
    textZh: "漁農自然護理署列明，由紅色小巴17號站步行約700米，由76K巴士站步行約980米。設30個私家車位，其中1個為傷健人士專用，並鼓勵訪客使用公共交通。",
    topics: ["green", "accessibility", "elderly"],
    status: "completed",
    placeIds: ["long-valley"],
  },
  {
    id: "recreation",
    sourceId: "ktnfln-about",
    heading: "Recreational Area and Business and Technology Park",
    headingZh: "康樂區及商業科技園",
    text: "The Recreational Area in the north-eastern portion of the NDA comprises Fung Kong Shan Park, a swimming pool, a sports centre and a sports ground/sports complex. A Business and Technology Park in the south-eastern part, with emphasis on commercial and R&D uses, is an important employment node.",
    textZh: "新發展區東北部的康樂區包括鳳崗山公園、游泳池、體育館及運動場／體育綜合館。東南部的商業及科技園以商業及研發用途為主，是重要的就業節點。",
    topics: ["green", "employment", "community"],
    status: "planned",
    placeIds: ["recreation-fks", "btp"],
  },
  {
    id: "noise",
    sourceId: "pland-odp",
    heading: "Traffic noise from Fanling Highway",
    headingZh: "粉嶺公路交通噪音",
    text: "Noise sensitive uses will be sited to avoid excessive traffic noise through non-domestic structures, noise barriers and setbacks. Residential uses are set back further from Fanling Highway, while government and community facilities planned along it are protected by noise barriers; 5 m vertical barriers, cantilevered barriers or full enclosures are proposed in some sections.",
    textZh: "噪音敏感用途會透過非住用建築物、隔音屏障及後移距離，避免受過量交通噪音影響。住宅用途會進一步遠離粉嶺公路，沿線的政府及社區設施則以隔音屏障保護；部分路段建議設5米垂直屏障、懸臂式屏障或全封閉式隔音罩。",
    topics: ["environment", "elderly"],
    status: "planned",
    placeIds: ["mwsc", "area-29-civic"],
  },

  // ── Scale, timing & governance ───────────────────────────────────────────
  {
    id: "scale-cedd",
    sourceId: "cedd-ktnfln",
    heading: "Scale and phasing of the NDA",
    headingZh: "新發展區規模及分期",
    text: "The KTN/FLN NDA covers 320 ha, implemented in a First Phase (73 ha) and Remaining Phase (247 ha). The first private housing development was completed at the end of 2022 and the first batch of public housing will be ready for population intake in 2026. Upon full development it will provide about 86,200 housing units (about 57,500 public), an additional population of about 227,000 and about 53,000 jobs. A government office complex is also planned in Kwu Tung North.",
    textZh: "古洞北／粉嶺北新發展區佔地320公頃，分第一階段（73公頃）及餘下階段（247公頃）推展。首個私營房屋項目於2022年底落成，首批公營房屋將於2026年入伙。全面發展後將提供約86,200個住宅單位（約57,500個公營）、新增人口約227,000及約53,000個就業機會。古洞北亦計劃興建政府辦公大樓。",
    topics: ["housing", "employment", "governance"],
    status: "under_construction",
    placeIds: ["area-19-housing"],
    timeline: "2026 first public housing intake",
  },
  {
    id: "population-odp",
    sourceId: "pland-odp",
    heading: "Planned population figure in the ODP",
    headingZh: "大綱圖的規劃人口",
    text: "The draft ODP estimates the total planned population of the Kwu Tung North area at about 119,700 upon full development, and states that first intake of population is expected to commence in 2025/26. Other project documents give different figures (for example about 131,600 additional population in the earlier study-stage description, and about 139,700 total planned population in the approved OZP No. S/KTN/4), so population estimates should be read as indicative. The 2025/26 intake date is superseded: the latest official timing (September 2026) is for public housing intake to start from the end of 2026.",
    textZh: "草圖估計古洞北區全面發展後的規劃人口約119,700人，首批人口預計於2025/26年遷入。其他項目文件數字有所不同（例如較早研究階段描述為新增約131,600人，核准分區計劃大綱圖編號S/KTN/4則為規劃總人口約139,700人），因此人口估算僅供參考。2025/26年的入伙時間已被取代：最新官方時間（2026年9月）為公營房屋於2026年底開始入伙。",
    topics: ["housing", "governance"],
    status: "planned",
    placeIds: [],
  },
  {
    id: "nm-bill",
    sourceId: "isd-nm-bill",
    heading: "Northern Metropolis Development Bill",
    headingZh: "《北部都會區發展條例草案》",
    text: "The Government gazetted the Northern Metropolis Development Bill on 3 July 2026 to further streamline planning and lands procedures, expedite construction works and facilitate industry operation. A public consultation ran from 24 March to 22 May 2026. The Government aims to achieve passage of the Bill within this year.",
    textZh: "政府於2026年7月3日刊憲《北部都會區發展條例草案》，以進一步精簡規劃及土地程序、加快工程及便利產業營運。公眾諮詢於2026年3月24日至5月22日進行，政府目標於年內通過草案。",
    topics: ["governance"],
    status: "proposed",
    placeIds: [],
  },
  {
    id: "past-views",
    sourceId: "tpb-9128",
    heading: "What residents asked for during earlier engagement",
    headingZh: "早前公眾參與中居民的訴求",
    text: "During the planning study's public engagement, some members of the public wanted a new hospital to relieve North District Hospital, while others wanted halls, libraries and community elderly homes, and asked for timely provision of facilities to avoid problems seen in Tin Shui Wai New Town. The NDAs were also planned to include integrated children and youth service centres, integrated family service centres, district and neighbourhood elderly centres and residential care homes for the elderly.",
    textZh: "規劃研究的公眾參與期間，部分市民希望興建新醫院以紓緩北區醫院壓力，亦有人希望設會堂、圖書館及社區安老院，並要求適時提供設施，避免重蹈天水圍新市鎮的問題。新發展區亦規劃設綜合青少年服務中心、綜合家庭服務中心、長者地區及鄰舍中心，以及安老院舍。",
    topics: ["community", "elderly", "healthcare", "governance"],
    status: "planned",
    placeIds: [],
  },

  // ── Statutory plan: approved OZP No. S/KTN/4 ─────────────────────────────
  {
    id: "ozp-approved",
    sourceId: "isd-ozp-approved",
    heading: "The approved statutory plan: Kwu Tung North OZP No. S/KTN/4",
    headingZh: "法定圖則：核准古洞北分區計劃大綱圖編號S/KTN/4",
    text: "The Chief Executive in Council approved the draft Kwu Tung North Outline Zoning Plan (OZP) under the Town Planning Ordinance, and the approved OZP No. S/KTN/4 was exhibited on 29 September 2023. The planning scheme area covers about 447 hectares, bounded by Shek Sheung River in the east, Castle Peak Road and Fanling Highway in the south, Tit Hang in the west and Tai Shek Mo (Crest Hill) in the north. The OZP is the statutory land-use plan for the area; the Outline Development Plan is a departmental plan that guides detailed layout.",
    textZh: "行政長官會同行政會議根據《城市規劃條例》核准古洞北分區計劃大綱草圖，核准圖編號S/KTN/4於2023年9月29日展示。規劃區佔地約447公頃，東至石上河，南至青山公路及粉嶺公路，西至鐵坑，北至大石磨。分區計劃大綱圖是該區的法定土地用途圖則；發展藍圖則屬部門圖則，用以指導詳細布局。",
    topics: ["governance"],
    status: "planned",
    placeIds: [],
    timeline: "approved 2023",
  },
  {
    id: "ozp-rezoning",
    sourceId: "legco-sktn4",
    heading: "Business park land rezoned for housing",
    headingZh: "商業科技園用地改劃作住宅",
    text: "The 2023 amendments rezoned sites in Areas 32 and 34 from \"Business and Technology Park\" to \"Residential (Group B)1\", and land near Yin Kong village from \"Comprehensive Development Area\" to \"Residential (Group B)2\" and \"Residential (Group C)1\", for private housing. The Government said the loss of business and technology land in Kwu Tung North would be offset by shifting that function to San Tin Technopole, as recommended in the Northern Metropolis Development Strategy. The Yin Kong sites would bring only about 1,700 new population.",
    textZh: "2023年的修訂把第32及34區用地由「商業及科技園」改劃為「住宅（乙類）1」，並把燕崗村附近土地由「綜合發展區」改劃為「住宅（乙類）2」及「住宅（丙類）1」，作私營房屋發展。政府表示，古洞北減少的商業及科技用地，會按《北部都會區發展策略》建議轉移至新田科技城。燕崗用地只會帶來約1,700新增人口。",
    topics: ["housing", "employment", "governance"],
    status: "planned",
    placeIds: ["btp"],
  },
  {
    id: "ozp-objections",
    sourceId: "legco-sktn4",
    heading: "Objections raised on the 2022 draft plan",
    headingZh: "市民對2022年草圖提出的反對意見",
    text: "During exhibition of the draft OZP No. S/KTN/3 from 21 October 2022, 26 valid representations and two comments were received; all 26 opposed various amendments. Grounds included: rezoning business park sites would reduce jobs; a site near Long Valley Nature Park might disturb birds' flight lines; higher building heights would weaken the stepped height profile; residential care homes for elderly residents rehoused from Dills Corner Garden should not be inside the government office/community complex; and more GIC facilities should be provided. The Town Planning Board considered them on 12 May 2023.",
    textZh: "分區計劃大綱草圖編號S/KTN/3於2022年10月21日起展示期間，共收到26份有效申述及兩份意見，26份申述均反對不同修訂項目。理由包括：改劃商業園用地會減少就業機會；塱原自然公園附近用地或會干擾雀鳥飛行路線；放寬建築物高度會削弱梯級式高度輪廓；安置得利歷花園長者的安老院舍不應設於政府辦公室／社區綜合大樓內；以及應增加政府、機構或社區設施。城市規劃委員會於2023年5月12日考慮有關申述。",
    topics: ["governance", "employment", "elderly", "green", "community"],
    status: "completed",
    placeIds: ["mwsc", "long-valley"],
  },
  {
    id: "ozp-area29-complex",
    sourceId: "legco-sktn4",
    heading: "Area 29 government office and community complex",
    headingZh: "第29區政府辦公室及社區綜合大樓",
    text: "The eastern portion of Area 29 is planned for a government office and community complex comprising mainly a government office building, a library, a sports centre, a community hall, a post office, a kindergarten and some social welfare facilities; the western portion has the Multi-welfare Services Complex and two schools next to it. The 2023 LegCo brief states that a 100-place Child Care Centre and an Integrated Children and Youth Services Centre will be provided in the complex.",
    textZh: "第29區東部規劃作政府辦公室及社區綜合大樓，主要包括政府辦公大樓、圖書館、體育館、社區會堂、郵政局、幼稚園及部分社會福利設施；西部設多福利服務綜合大樓，旁邊有兩所學校。2023年立法會參考資料摘要指出，綜合大樓將設一所提供100個名額的幼兒中心及一間綜合青少年服務中心。",
    topics: ["community", "education", "elderly"],
    status: "planned",
    placeIds: ["area-29-civic", "mwsc"],
  },
  {
    id: "ozp-schools",
    sourceId: "legco-sktn4",
    heading: "Six primary and four secondary schools",
    headingZh: "六所小學及四所中學",
    text: "Six primary schools and four secondary schools are planned within the NDA, close to residential developments: one primary and one secondary school in Area 29; two primary schools and one secondary school in Area 22 north-east of the Town Centre; two primary and two secondary schools next to the swimming pool and sports centre in Areas 8, 9 and 11 in the North Residential Area; and a primary school near Fung Kong Shan in Area 13.",
    textZh: "新發展區內規劃六所小學及四所中學，鄰近住宅發展：第29區一所小學及一所中學；市中心東北面第22區兩所小學及一所中學；北部住宅區第8、9及11區游泳池及體育館旁兩所小學及兩所中學；以及鳳崗山附近第13區一所小學。",
    topics: ["education", "community"],
    status: "planned",
    placeIds: ["area-29-civic", "north-residential", "town-centre"],
  },
  {
    id: "ozp-population",
    sourceId: "legco-sktn4",
    heading: "Planned population and housing mix in the approved plan",
    headingZh: "核准圖的規劃人口及房屋組合",
    text: "The Explanatory Statement of the approved OZP estimates the area's population at about 7,100 (2016 by-census) and the total planned population at about 139,700. The planned population of the KTN NDA is around 62:38 in public and private housing; across the KTN and FLN NDAs the public-to-private ratio by number of flats is about 67:33. Some sites are reserved for public rental housing or subsidised sale flats, with the mix decided on implementation.",
    textZh: "核准分區計劃大綱圖的說明書估計，該區人口約7,100人（2016年中期人口統計），規劃總人口約139,700人。古洞北新發展區公營與私營房屋的規劃人口比例約為62:38；古洞北及粉嶺北新發展區按單位數目計的公私營房屋比例約為67:33。部分用地預留作公屋或資助出售房屋，實際組合於推展時決定。",
    topics: ["housing", "governance"],
    status: "planned",
    placeIds: ["area-19-housing"],
  },
  {
    id: "ozp-hospital-2023",
    sourceId: "legco-sktn4",
    heading: "2023 plan reserved 4.35 ha in Area 28 for a hospital",
    headingZh: "2023年圖則在第28區預留4.35公頃作醫院",
    text: "The 2023 LegCo brief stated that a site of 4.35 hectares in Area 28 was reserved for a new hospital development, with building height restrictions relaxed. This was before the December 2024 LegCo reply, in which the Government said it plans to replace the Kwu Tung North hospital with an integrated hospital at Ngau Tam Mei.",
    textZh: "2023年立法會參考資料摘要指出，第28區預留4.35公頃用地作新醫院發展，並放寬建築物高度限制。此說法早於2024年12月的立法會答覆；政府在該答覆中表示計劃以牛潭尾綜合醫院取代古洞北醫院。",
    topics: ["healthcare"],
    status: "superseded",
    placeIds: ["area-28-health", "ntm-hospital"],
  },
  {
    id: "ozp-recreation",
    sourceId: "legco-sktn4",
    heading: "Sports ground, swimming pool and youth camp sites",
    headingZh: "運動場、游泳池及青少年營地用地",
    text: "Area 10 is reserved for a standard swimming pool and a sports centre; Area 1 in the north-west for a sports ground/sports complex accommodating up to 10,000 persons; and a site north of Fung Kong Shan in Area 4 for a Potential Activity Centre with a youth camp and adventure training facilities.",
    textZh: "第10區預留作標準游泳池及體育館；西北部第1區預留作可容納多達10,000人的運動場／體育綜合館；第4區鳳崗山以北用地預留作活動中心，設青少年營地及歷奇訓練設施。",
    topics: ["green", "community"],
    status: "planned",
    placeIds: ["recreation-fks"],
  },
  {
    id: "ozp-riverside",
    sourceId: "legco-sktn4",
    heading: "Riverside promenade and heritage",
    headingZh: "河畔長廊及文物",
    text: "Regional open space along the western banks of Sheung Yue River and Shek Sheung River will become a continuous riverside promenade for passive recreation, integrated with the footpath and cycle track network. Heritage in the area includes the Hau Ku Shek Ancestral Hall (Declared Monument) and the Grade 3 Hung Shing Temple and Pai Fung Temple; the Grade 3 historic building Yeung Yuen at the southern end of the promenade should be incorporated into its design.",
    textZh: "雙魚河及石上河西岸的區域休憩用地將發展為連貫的河畔長廊，作靜態康樂用途，並與行人路及單車徑網絡融合。區內文物包括居石侯公祠（法定古蹟），以及三級歷史建築洪聖宮及排峰古廟；位於長廊南端的三級歷史建築Yeung Yuen應納入長廊設計。",
    topics: ["green", "community"],
    status: "planned",
    placeIds: ["long-valley"],
  },
  {
    id: "ozp-village-resite",
    sourceId: "legco-sktn4",
    heading: "Village resite area near Ho Sheung Heung",
    headingZh: "河上鄉附近的鄉村遷置區",
    text: "A site of about 1.1 ha in Area 36 near Ho Sheung Heung Village is zoned \"Village Type Development (1)\" to provide land for reprovisioning village houses affected by the NDA under the Village Removal Terms. The two recognised villages in the area, Ho Sheung Heung and Yin Kong, remain within \"Village Type Development\" zones.",
    textZh: "第36區河上鄉附近約1.1公頃用地劃為「鄉村式發展（1）」，按遷村條款為受新發展區影響的村屋提供重置用地。區內兩條認可鄉村河上鄉及燕崗仍劃為「鄉村式發展」地帶。",
    topics: ["housing", "community"],
    status: "planned",
    placeIds: ["long-valley"],
  },

  // ── Works progress (CEDD) ────────────────────────────────────────────────
  {
    id: "works-first-phase",
    sourceId: "cedd-works",
    heading: "First Phase site formation and infrastructure",
    headingZh: "第一階段土地平整及基礎設施工程",
    text: "Contract ND/2019/01 (commenced 6 December 2019, completion 2026 tentative, $2.888 billion) covers site formation of the KTN First Phase and infrastructure including footpaths, cycle tracks, a subway, service reservoirs, district cooling pipework and noise barriers/enclosures. Contract ND/2019/02 (commenced 17 February 2020, completion 2026 tentative) covers roads and drains to Shek Wu Hui, a Long Valley Nature Park visitor centre, a footbridge across Sheung Yue River and a village resite area.",
    textZh: "合約ND/2019/01（2019年12月6日動工，暫定2026年完成，28.88億元）涵蓋古洞北第一階段土地平整及基礎設施，包括行人路、單車徑、行人隧道、配水庫、區域供冷管道及隔音屏障／隔音罩。合約ND/2019/02（2020年2月17日動工，暫定2026年完成）涵蓋往石湖墟的道路及排水工程、塱原自然公園訪客中心、橫跨雙魚河的行人天橋及鄉村遷置區。",
    topics: ["transport", "accessibility", "environment"],
    status: "under_construction",
    placeIds: ["town-centre", "long-valley"],
    timeline: "2026",
  },
  {
    id: "works-remaining",
    sourceId: "cedd-works",
    heading: "Remaining Phase site works (South and North)",
    headingZh: "餘下階段土地平整工程（南及北）",
    text: "Remaining Phase site formation and infrastructure works (South) commenced on 23 August 2024 for completion in mid 2030 (tentative), including roads connecting to Castle Peak Road and Fanling Highway, footbridges at Road P2, a common utility enclosure and a visitor centre. Works (North) commenced on 16 December 2025 for completion in mid 2031 (tentative), including roads, noise barriers, footpaths, cycle tracks and flood prevention works.",
    textZh: "餘下階段土地平整及基礎設施工程（南）於2024年8月23日動工，暫定2030年中完成，包括連接青山公路及粉嶺公路的道路、P2路行人天橋、共同管道及訪客中心。工程（北）於2025年12月16日動工，暫定2031年中完成，包括道路、隔音屏障、行人路、單車徑及防洪工程。",
    topics: ["transport", "accessibility", "housing"],
    status: "under_construction",
    placeIds: ["north-residential"],
    timeline: "mid 2030 – mid 2031",
  },
  {
    id: "works-fanling-highway",
    sourceId: "cedd-works",
    heading: "Fanling Highway widening and footbridges to Kwu Tung South",
    headingZh: "粉嶺公路擴闊及往古洞南的行人天橋",
    text: "Improvement works of Fanling Highway (Kwu Tung Portion) commenced on 14 August 2024 for completion in mid 2030 (tentative). They include widening the highway, building footbridges across Fanling Highway (Kwu Tung Portion), Kwu Tung Interchange, modifying Kwu Tung Road, building Road L3, and noise enclosures, noise barriers and low-noise road surfacing. The Pak Shek Au Portion, with another footbridge across the highway, commenced on 19 January 2026 for completion in 2031 (tentative).",
    textZh: "粉嶺公路（古洞段）改善工程於2024年8月14日動工，暫定2030年中完成，包括擴闊公路、興建橫跨粉嶺公路（古洞段）的行人天橋、古洞交匯處、改建古洞路、興建L3路，以及隔音罩、隔音屏障及低噪音路面。白石凹段（包括另一條橫跨公路的行人天橋）於2026年1月19日動工，暫定2031年完成。",
    topics: ["transport", "accessibility", "environment", "elderly"],
    status: "under_construction",
    placeIds: ["footbridges-kts"],
    timeline: "mid 2030 – 2031",
  },
  {
    id: "lvnp-works",
    sourceId: "cedd-first-stage",
    heading: "Long Valley works and egretries",
    headingZh: "塱原工程及鷺鳥林",
    text: "The first-stage project includes a nature park at Long Valley of about 37 ha with a visitor centre and a footbridge of about 50 metres across Sheung Yue River linking the park and the visitor centre; reprovisioning of two egretry sites in the FLN NDA and enhancement of an existing egretry in the KTN NDA; and site formation of about 2.3 ha for a village resite area and a district police station. The nature park contract was completed on 28 March 2024.",
    textZh: "第一期工程包括約37公頃的塱原自然公園、訪客中心及一條長約50米、橫跨雙魚河連接公園與訪客中心的行人天橋；重置粉嶺北新發展區兩個鷺鳥林及改善古洞北新發展區一個現有鷺鳥林；以及平整約2.3公頃土地作鄉村遷置區及分區警署。自然公園合約於2024年3月28日完成。",
    topics: ["green", "environment"],
    status: "completed",
    placeIds: ["long-valley"],
  },

  // ── Public housing & intake ──────────────────────────────────────────────
  {
    id: "kwu-chun-estate",
    sourceId: "ndc-kwu-chun",
    heading: "Kwu Chun Estate (古雋邨) in Area 19",
    headingZh: "第19區古雋邨",
    text: "The Housing Authority is building 12 residential blocks with 9,304 public rental housing flats, a social welfare facility and a car park building on the Area 19 site. The estate was named Kwu Chun Estate after a naming competition that ended on 15 September 2024. It is completed in three stages: Stage 1 (five blocks, the welfare facility and car park) was expected to complete in Q1 2026, Stage 2 (one block) in Q4 2026, and Stage 3 (six blocks) in Q3 2027.",
    textZh: "房委會於第19區用地興建12座住宅樓宇（共9,304個公屋單位）、一所社福設施及停車場大樓。屋邨經2024年9月15日結束的命名比賽定名為「古雋邨」，分三個階段落成：第一階段（五座樓宇、社福設施及停車場大樓）預計2026年第1季竣工，第二階段（一座）預計2026年第4季竣工，第三階段（六座）預計2027年第3季竣工。",
    topics: ["housing"],
    status: "under_construction",
    placeIds: ["area-19-housing"],
    timeline: "Q1 2026 – Q3 2027",
  },
  {
    id: "ha-northern-metropolis",
    sourceId: "ha-dimensions-2608",
    heading: "First public rental flats in the Northern Metropolis",
    headingZh: "北部都會區首批公屋",
    text: "The first batch of public rental housing units in the Northern Metropolis comprises around 5,000 units in Phase 1 of Kwu Chun Estate in Kwu Tung North and around 3,100 units in Phase 1 of Fung Wong Leng Estate in Fanling North. In August 2026 the Housing Authority said residents would move in by phases starting that August. About 70,000 public units, about 40% of public housing production from 2026/27 to 2030/31, are in the Northern Metropolis. Kwu Tung North estates are designed to connect to hiking trails on nearby hills.",
    textZh: "北部都會區首批公屋包括古洞北古雋邨第一期約5,000個單位及粉嶺北鳳凰嶺邨第一期約3,100個單位。房委會於2026年8月表示，住戶將於當年8月起分階段入伙。2026/27至2030/31年度約70,000個公營單位（約佔公營房屋總建屋量40%）位於北部都會區。古洞北屋邨的設計會連接附近山嶺的遠足徑。",
    topics: ["housing", "green"],
    status: "under_construction",
    placeIds: ["area-19-housing"],
    timeline: "intake from 2026",
  },
  {
    id: "kwu-chun-intake",
    sourceId: "legco-visit-2609",
    heading: "Latest intake timing and LegCo's call for facilities",
    headingZh: "最新入伙時間及立法會對設施的要求",
    text: "On 10 September 2026 LegCo Members learnt that Kwu Chun Estate phase one, about 5,000 units, will be ready for intake in phases starting from the end of this year, and that Kwu Tung Station is expected to commence service in 2027. Members discussed community facilities such as markets, shopping centres, public transport facilities and schools, and urged the Administration to ensure community facilities are in place when residents start to move in. An earlier Housing Authority publication (14 August 2026) had given a start from August 2026; this September statement is the most recent official timing.",
    textZh: "立法會議員於2026年9月10日察悉，古雋邨第一期約5,000個單位將於今年年底開始分階段入伙，古洞站預計於2027年投入服務。議員就街市、商場、公共運輸設施及學校等社區設施交換意見，並促請當局確保社區設施在居民入伙時落實到位。房委會較早前的刊物（2026年8月14日）曾表示由2026年8月起入伙；此9月的說法為最新官方時間。",
    topics: ["housing", "community", "transport", "education"],
    status: "under_construction",
    placeIds: ["area-19-housing", "ktu-station", "town-centre"],
    timeline: "intake from end-2026",
  },
  {
    id: "housing-12000",
    sourceId: "sdev-remarks-2609",
    heading: "About 12,000 flats completing in 2026–27",
    headingZh: "2026至27年約12,000個單位落成",
    text: "The Secretary for Development said (in Chinese) that land for housing in the Kwu Tung North NDA can accommodate 50,000 public and private units, and about 12,000 units will be completed for intake this year and next, including public housing, a dedicated rehousing estate for squatter occupants affected by clearance, and several private housing projects. Kwu Tung Station is expected to open next year to match residents' intake.",
    textZh: "發展局局長表示，古洞北新發展區的房屋用地可承載50,000個公私營房屋單位，今年及明年會有12,000個單位陸續落成入伙，當中包括公營房屋、專為受清拆發展影響的寮屋住戶而設的專用安置屋邨，以及幾個私人房屋發展項目。東鐵古洞站預計明年啓用，以配合居民入伙時間。",
    topics: ["housing", "transport"],
    status: "under_construction",
    placeIds: ["area-19-housing", "ktu-station"],
    timeline: "2026–2027",
  },

  // ── Government complex, pavilion & urban-rural integration ──────────────
  {
    id: "joint-user-complex",
    sourceId: "sdev-remarks-2609",
    heading: "Joint-user complex, NM pavilion, museum and swimming venue",
    headingZh: "聯用綜合大樓、北都核心展館、博物館及游泳館",
    text: "The Secretary for Development said the first Government joint-user complex and joint-user office building in the NDAs, funded by LegCo this year, have started construction and are expected to complete in phases from end-2029. A Northern Metropolis core pavilion, the largest of the NM exhibition halls, is being built in Kwu Tung North for completion in the first half of next year. Sites are also reserved for a museum on national development and achievements and a swimming venue able to host international competitions.",
    textZh: "發展局局長表示，坐落北都新發展區的首座政府聯用綜合大樓及聯用辦公大樓今年獲立法會撥款後已開始施工，預計於二○二九年底起分階段落成。古洞北正興建規模最大的北都核心展館，預期明年上半年落成。區內亦預留用地發展一個介紹國家發展和成就的博物館，以及一個可舉辦國際級別比賽的游泳館。",
    topics: ["community", "employment", "governance"],
    status: "under_construction",
    placeIds: ["area-29-civic"],
    timeline: "2027 – end-2029",
  },
  {
    id: "urban-rural",
    sourceId: "legco-visit-2609",
    heading: "Urban-rural integration: Yin Kong pilot and $200 million fund",
    headingZh: "城鄉共融：燕崗試點及二億元基金",
    text: "The Government proposed a $200 million \"NM Urban-Rural Integration Fund\" pilot to support NGOs taking forward urban-rural integration projects, and piloting relaxed \"Village Type Development\" planning restrictions in Yin Kong Village so village houses may be converted into restaurants, retail shops or guesthouses. LegCo Members raised how to help villagers retrofit houses and the transport and sewerage upgrades needed. Nearby, the Grade II Lady Ho Tung Welfare Centre (built 1933) was revitalised into an eco-learning institute in 2023.",
    textZh: "政府建議成立二億元「北都城鄉共融基金」先導計劃，資助非政府機構推行城鄉共融項目，並在燕崗村試行放寬「鄉村式發展」的規劃限制，容許村內屋宇改作食肆、零售商店或旅館。立法會議員提出如何協助村民改裝屋宇，以及所需的交通及污水基建提升。附近於1933年建成的二級歷史建築何東夫人醫局已於2023年活化為生態研習中心。",
    topics: ["community", "employment", "green", "governance"],
    status: "proposed",
    placeIds: ["long-valley"],
  },
];

export const CHUNK_BY_ID = new Map(CHUNKS.map((c) => [c.id, c]));
