import type { Chunk } from "@/lib/types";

/**
 * Curated knowledge base for Kwu Tung North. Every chunk is a close paraphrase
 * of the cited source; figures are copied verbatim from that source.
 */
export const CHUNKS: Chunk[] = [
  // ── Transport ────────────────────────────────────────────────────────────
  {
    id: "ktu-erl-station",
    sourceId: "hyd-nol",
    heading: "Kwu Tung Station on the East Rail Line",
    headingZh: "東鐵綫古洞站",
    text: "Kwu Tung Station is an intermediate station between Sheung Shui Station and Lok Ma Chau Station on the Lok Ma Chau Spur Line, and will connect to the Northern Link Main Line. Construction commenced in 2023 and the station is expected to come into operation in 2027 as scheduled.",
    textZh: "古洞站是落馬洲支綫上水站與落馬洲站之間的中途站，並將連接北環綫主綫。工程於2023年展開，預計於2027年如期投入服務。",
    topics: ["transport", "crossborder"],
    status: "under_construction",
    placeIds: ["ktu-station", "erl-spur", "sheung-shui"],
    timeline: "2027",
  },
  {
    id: "ktu-topout",
    sourceId: "mtr-topout",
    heading: "Station topped out; shorter rail journey to Sheung Shui",
    headingZh: "古洞站平頂；往上水的鐵路車程將大幅縮短",
    text: "A topping-out ceremony on 19 November 2025 marked the substantial completion of civil works at Kwu Tung Station on the East Rail Line; the project has entered the electrical and mechanical works stage and is targeted for completion in 2027. MTR states that, compared with existing public transport options, journey time between the Kwu Tung North NDA and Sheung Shui by rail will be substantially shortened.",
    textZh: "東鐵綫古洞站於2025年11月19日舉行平頂儀式，標誌土木工程大致完成，工程已進入機電階段，目標2027年完成。港鐵表示，與現有公共交通相比，古洞北新發展區往返上水的鐵路車程將大幅縮短。",
    topics: ["transport"],
    status: "under_construction",
    placeIds: ["ktu-station"],
    timeline: "2027",
  },
  {
    id: "ktu-location",
    sourceId: "mtr-ktu",
    heading: "Station sits in the future Town Centre",
    headingZh: "車站位於未來市中心",
    text: "The proposed Kwu Tung Station is located at the junction of the existing Ma Tso Lung Road and Ho Sheung Heung Road, which is also the town centre of the future Kwu Tung North NDA, near the NDA's residential, retail, leisure, social services and community facilities. Kwu Tung Station on the East Rail Line and Kwu Tung Station on the Northern Link will be next to each other and inter-connected, so passengers can interchange between the two lines.",
    textZh: "擬建古洞站位於現有馬草壟路與河上鄉路交界，即未來古洞北新發展區市中心，鄰近住宅、零售、休閒、社會服務及社區設施。東鐵綫古洞站與北環綫古洞站將相鄰並互相連接，方便乘客轉乘。",
    topics: ["transport", "community", "accessibility"],
    status: "under_construction",
    placeIds: ["ktu-station", "town-centre"],
  },
  {
    id: "nol-main-line",
    sourceId: "hyd-nol",
    heading: "Northern Link Main Line",
    headingZh: "北環綫主綫",
    text: "The Northern Link Main Line is a railway of about 10.7 km connecting Kam Sheung Road Station and Kwu Tung Station, with three intermediate stations at San Tin, Ngau Tam Mei and Au Tau. Construction commenced in 2025 for commissioning by 2034 or earlier.",
    textZh: "北環綫主綫全長約10.7公里，連接錦上路站與古洞站，設有新田、牛潭尾及凹頭三個中途站。工程於2025年展開，目標2034年或之前通車。",
    topics: ["transport", "employment"],
    status: "under_construction",
    placeIds: ["nol-main", "ktu-station"],
    timeline: "by 2034",
  },
  {
    id: "nol-journey-time",
    sourceId: "isd-nol-scheme",
    heading: "Expected journey time to Kam Sheung Road",
    headingZh: "往錦上路的預計車程",
    text: "When the Northern Link Main Line comes into operation, travel time between Kam Sheung Road Station and Kwu Tung Station is expected to be substantially reduced from the current 60 to 80 minutes during peak hours to about 12 minutes. The Main Line will connect the Tuen Ma Line and East Rail Line, forming a railway loop linking the New Territories and the Kowloon urban area.",
    textZh: "北環綫主綫通車後，錦上路站至古洞站的繁忙時間車程預計由現時60至80分鐘大幅縮短至約12分鐘。主綫將連接屯馬綫與東鐵綫，形成連接新界與九龍市區的鐵路環綫。",
    topics: ["transport", "employment"],
    status: "under_construction",
    placeIds: ["nol-main"],
    timeline: "by 2034",
  },
  {
    id: "nol-phasing",
    sourceId: "mtr-nol-explained",
    heading: "How the Northern Link is being delivered in parts",
    headingZh: "北環綫分部分推展",
    text: "Part 1 of the Project Agreement covers construction of Kwu Tung, Au Tau and Kam Sheung Road stations and the tunnel sections from Kwu Tung to San Tin and Au Tau to Kam Sheung Road. San Tin and Ngau Tam Mei stations, the remaining Main Line works and the depot integrated with the Spur Line will be addressed in a Part 2 Project Agreement, with the aim of commissioning the Main Line and Spur Line together no later than 2034.",
    textZh: "項目協議第一部分涵蓋古洞、凹頭及錦上路站，以及古洞至新田、凹頭至錦上路的隧道段。新田站、牛潭尾站、主綫其餘工程及與支綫整合的車廠將於第二部分項目協議處理，目標主綫及支綫於2034年或之前同步通車。",
    topics: ["transport"],
    status: "proposed",
    placeIds: ["nol-main"],
    timeline: "no later than 2034",
  },
  {
    id: "roads",
    sourceId: "cedd-ktnfln",
    heading: "Road improvements",
    headingZh: "道路改善工程",
    text: "The Fanling Bypass (Eastern Section) serving Fanling North was completed and commissioned in May 2026. Widening of Fanling Highway (Kwu Tung Section), the Fanling Bypass Western Section and a flyover along Po Shek Wu Road to Fanling Highway (westbound) will be carried out under the Remaining Phase for completion in 2031.",
    textZh: "服務粉嶺北的粉嶺繞道（東段）已於2026年5月落成啟用。粉嶺公路（古洞段）擴闊、粉嶺繞道西段及寶石湖路往粉嶺公路（西行）的天橋將於餘下階段進行，目標2031年完成。",
    topics: ["transport"],
    status: "planned",
    placeIds: [],
    timeline: "2031",
  },

  // ── Walkability & accessibility ──────────────────────────────────────────
  {
    id: "odp-500m",
    sourceId: "pland-odp",
    heading: "Most homes planned within 500 m of the station",
    headingZh: "大部分住宅規劃於車站500米範圍內",
    text: "High density residential developments, workplaces, leisure and public service facilities are concentrated within the 500 m catchments of the proposed railway station and public transport interchange in the Town Centre, to offer the majority of future residents convenient access to public transport. Subsidised housing sites in Areas 19, 21 and 24 (Town Centre) and Areas 12 and 13 (North Residential Area) are all located within 500 m walking distance of the proposed railway station.",
    textZh: "高密度住宅、工作地點、休閒及公共服務設施集中於市中心擬建鐵路站及公共運輸交匯處的500米範圍內，讓大部分未來居民方便使用公共交通。第19、21、24區（市中心）及第12、13區（北部住宅區）的資助房屋用地均位於擬建鐵路站500米步行距離內。",
    topics: ["accessibility", "transport", "housing"],
    status: "planned",
    placeIds: ["area-19-housing", "north-residential", "ktu-station"],
  },
  {
    id: "odp-footbridges",
    sourceId: "pland-odp",
    heading: "Footbridges to existing communities",
    headingZh: "連接現有社區的行人天橋",
    text: "Pedestrian linkages in the form of footbridges to Kwu Tung South across the Fanling Highway, and footbridges to Ho Sheung Heung and Yin Kong, are proposed to provide easy access for pedestrians between these areas and the Town Centre. A multi-level pedestrian connection integrating elevated and at-grade routes is planned to connect the public transport interchange.",
    textZh: "規劃建議興建橫跨粉嶺公路往古洞南的行人天橋，以及往河上鄉和燕崗的行人天橋，方便行人往返市中心。另規劃結合高架及地面的多層行人連接系統，連接公共運輸交匯處。",
    topics: ["accessibility", "transport", "elderly"],
    status: "proposed",
    placeIds: ["footbridges-kts", "town-centre"],
  },
  {
    id: "odp-pedestrian-env",
    sourceId: "pland-odp",
    heading: "Car-free Town Centre and continuous footpaths",
    headingZh: "無車市中心及連貫行人路",
    text: "Footpaths will be pedestrian friendly, continuous and landscaped. The Town Centre would be pedestrianised to provide a motor vehicle-free walking environment by placing vehicular roads away from it, with a cruciform pedestrian shopping street. Cycle tracks run along open space spines and riverside promenades, with cycle parking proposed close to the railway station and public transport interchange.",
    textZh: "行人路將以行人友善、連貫及綠化為原則。市中心將行人化，車路遠離市中心，營造無車步行環境，並設十字形行人購物街。單車徑沿休憩空間主軸及河畔長廊設置，鐵路站及公共運輸交匯處附近亦建議設單車停泊處。",
    topics: ["accessibility", "green", "transport"],
    status: "planned",
    placeIds: ["town-centre"],
  },

  // ── Community & elderly facilities ───────────────────────────────────────
  {
    id: "civic-hub",
    sourceId: "pland-odp",
    heading: "Area 29 civic hub",
    headingZh: "第29區社區樞紐",
    text: "A site in Area 29 is reserved for a district library, a sports centre, a community hall, a post office, some social welfare facilities and other government facilities. With good access to the proposed railway station, the public transport interchange and connections to Kwu Tung South, it will serve as a hub of civic activities and social services. The land to its west abutting Road D1 is planned for the Multi-welfare Services Complex.",
    textZh: "第29區用地預留作地區圖書館、體育館、社區會堂、郵政局、部分社會福利設施及其他政府設施。該處鄰近擬建鐵路站、公共運輸交匯處並連接古洞南，將成為公民活動及社會服務樞紐。其西面毗鄰D1路的土地規劃作多福利服務綜合大樓。",
    topics: ["community", "elderly"],
    status: "planned",
    placeIds: ["area-29-civic", "mwsc"],
  },
  {
    id: "mwsc-detail",
    sourceId: "devb-1497",
    heading: "Multi-welfare Services Complex",
    headingZh: "多福利服務綜合大樓",
    text: "The Multi-welfare Services Complex in Kwu Tung North will provide Day Care Units for the Elderly and about 1,750 places for the elderly, plus a Day Activity Centre cum Hostel for Severely Mentally Handicapped Persons and a Care and Attention Home for Severely Disabled Persons. It will also reprovision eligible elderly residents of existing residential care homes at Dills Corner Garden affected by the NDA. Because it sits beside Fanling Highway, it uses an H-shaped layout and architectural fins to shield traffic noise.",
    textZh: "古洞北多福利服務綜合大樓將提供長者日間護理單位及約1,750個長者宿位，另設嚴重弱智人士日間活動中心暨宿舍及嚴重殘疾人士護理院，並安置受新發展區影響的得利歷花園現有安老院舍合資格長者。由於毗鄰粉嶺公路，大樓採用H形設計及建築鰭片以阻隔交通噪音。",
    topics: ["elderly", "community", "healthcare", "accessibility"],
    status: "planned",
    placeIds: ["mwsc"],
  },
  {
    id: "area19-facilities",
    sourceId: "devb-467",
    heading: "Facilities next to the Area 19 public housing",
    headingZh: "第19區公營房屋旁的設施",
    text: "Next to the public housing site in Area 19 will be a public market, a Multi-welfare Services Complex of the Social Welfare Department, schools, a sports centre, a library, a community centre, public transport interchanges and the future Kwu Tung Station on the Northern Link.",
    textZh: "第19區公營房屋用地旁將設有公眾街市、社會福利署多福利服務綜合大樓、學校、體育館、圖書館、社區中心、公共運輸交匯處及未來北環綫古洞站。",
    topics: ["community", "elderly", "education", "transport"],
    status: "planned",
    placeIds: ["area-19-housing", "mwsc", "town-centre"],
  },
  {
    id: "town-centre-elderly",
    sourceId: "pland-odp",
    heading: "Kindergartens and a district elderly centre in the Town Centre",
    headingZh: "市中心的幼稚園及長者地區中心",
    text: "Social and community facilities proposed within the two Town Centre sites beside the Town Plaza include a nursery and kindergarten in the western site, and a nursery and kindergarten and a District Elderly Community Centre in the eastern site.",
    textZh: "市鎮廣場旁兩幅市中心用地內建議設置社區設施，包括西面用地的幼兒園暨幼稚園，以及東面用地的幼兒園暨幼稚園和長者地區中心。",
    topics: ["elderly", "education", "community"],
    status: "planned",
    placeIds: ["town-centre"],
  },
  {
    id: "schools",
    sourceId: "pland-odp",
    heading: "Schools",
    headingZh: "學校",
    text: "The Kwu Tung North ODP proposes primary and secondary schools within the NDA, including sites in the North Residential Area, planned according to the Hong Kong Planning Standards and Guidelines.",
    textZh: "古洞北分區計劃大綱圖建議在新發展區內設置中小學，包括北部住宅區的用地，並按《香港規劃標準與準則》規劃。",
    topics: ["education", "community"],
    status: "planned",
    placeIds: ["north-residential"],
  },

  // ── Healthcare ───────────────────────────────────────────────────────────
  {
    id: "hospital-superseded",
    sourceId: "legco-lcq17",
    heading: "Kwu Tung North hospital replaced by Ngau Tam Mei plan",
    headingZh: "古洞北醫院方案由牛潭尾計劃取代",
    text: "Because the site reserved for healthcare facilities in the Kwu Tung North NDA is relatively small with constraints on expansion, the Government plans to replace the previously proposed new hospital at Kwu Tung North with a new integrated medical teaching and research hospital at Ngau Tam Mei, on a site of about nine hectares with about 3,000 beds. Details and implementation schedules are being studied under the review of the Second Hospital Development Plan.",
    textZh: "由於古洞北新發展區預留的醫療設施用地面積較小且擴展受限，政府計劃以牛潭尾一所新的綜合醫學教學及研究醫院（用地約九公頃、約3,000張病床）取代原先建議的古洞北新醫院。相關細節及推展時間表正於第二個醫院發展計劃檢討中研究。",
    topics: ["healthcare", "elderly"],
    status: "superseded",
    placeIds: ["area-28-health", "ntm-hospital"],
  },
  {
    id: "ndh-expansion",
    sourceId: "legco-lcq17",
    heading: "North District Hospital expansion",
    headingZh: "北區醫院擴建",
    text: "Main works of the North District Hospital expansion commenced in September 2024, aiming to complete the new acute block in 2028 for gradual commissioning of services starting from 2029.",
    textZh: "北區醫院擴建主體工程已於2024年9月展開，目標於2028年完成新急症大樓，並由2029年起逐步投入服務。",
    topics: ["healthcare", "elderly"],
    status: "under_construction",
    placeIds: ["ndh"],
    timeline: "2028–2029",
  },
  {
    id: "odp-area28",
    sourceId: "pland-odp",
    heading: "Area 28 healthcare reservation on the plan",
    headingZh: "大綱圖上的第28區醫療用地",
    text: "The draft ODP still shows a site in the south-western part of the NDA (Area 28) reserved for a proposed hospital, polyclinic and general clinic/health centre to serve the KTN/FLN NDA, the wider population and nearby residents.",
    textZh: "草圖仍顯示新發展區西南部（第28區）預留作擬建醫院、普通科診所及健康中心，服務古洞北／粉嶺北新發展區及附近居民。",
    topics: ["healthcare"],
    status: "under_review",
    placeIds: ["area-28-health"],
  },

  // ── Green space & environment ────────────────────────────────────────────
  {
    id: "lvnp",
    sourceId: "lvnp",
    heading: "Long Valley Nature Park",
    headingZh: "塱原自然公園",
    text: "Long Valley Nature Park is about 37 ha, divided into a Visitor Zone (5 ha), Agriculture Zone (11 ha) and Biodiversity Zone (21 ha). It was developed as a mitigation for the ecological impact of the Kwu Tung North and Fanling North NDAs, with construction starting in late 2019, and opened in November 2024.",
    textZh: "塱原自然公園佔地約37公頃，分為訪客區（5公頃）、農業區（11公頃）及生物多樣性區（21公頃），作為古洞北及粉嶺北新發展區生態影響的緩解措施，於2019年底動工，2024年11月開放。",
    topics: ["green", "environment"],
    status: "completed",
    placeIds: ["long-valley"],
  },
  {
    id: "lvnp-access",
    sourceId: "afcd-lvnp",
    heading: "Getting to Long Valley Nature Park today",
    headingZh: "現時前往塱原自然公園",
    text: "AFCD lists walking distances from public transport of about 700 m from the red minibus 17 stop and about 980 m from the bus 76K stop. There are 30 private car parking spaces including 1 designated space for people with disabilities, and visitors are encouraged to use public transport.",
    textZh: "漁農自然護理署列明，由紅色小巴17號站步行約700米，由76K巴士站步行約980米。設30個私家車位，其中1個為傷健人士專用，並鼓勵訪客使用公共交通。",
    topics: ["green", "accessibility", "elderly"],
    status: "completed",
    placeIds: ["long-valley"],
  },
  {
    id: "recreation",
    sourceId: "ktnfln-about",
    heading: "Recreational Area and Business and Technology Park",
    headingZh: "康樂區及商業科技園",
    text: "The Recreational Area in the north-eastern portion of the NDA comprises Fung Kong Shan Park, a swimming pool, a sports centre and a sports ground/sports complex. A Business and Technology Park in the south-eastern part, with emphasis on commercial and R&D uses, is an important employment node.",
    textZh: "新發展區東北部的康樂區包括鳳崗山公園、游泳池、體育館及運動場／體育綜合館。東南部的商業及科技園以商業及研發用途為主，是重要的就業節點。",
    topics: ["green", "employment", "community"],
    status: "planned",
    placeIds: ["recreation-fks", "btp"],
  },
  {
    id: "noise",
    sourceId: "pland-odp",
    heading: "Traffic noise from Fanling Highway",
    headingZh: "粉嶺公路交通噪音",
    text: "Noise sensitive uses will be sited to avoid excessive traffic noise through non-domestic structures, noise barriers and setbacks. Residential uses are set back further from Fanling Highway, while government and community facilities planned along it are protected by noise barriers; 5 m vertical barriers, cantilevered barriers or full enclosures are proposed in some sections.",
    textZh: "噪音敏感用途會透過非住用建築物、隔音屏障及後移距離，避免受過量交通噪音影響。住宅用途會進一步遠離粉嶺公路，沿線的政府及社區設施則以隔音屏障保護；部分路段建議設5米垂直屏障、懸臂式屏障或全封閉式隔音罩。",
    topics: ["environment", "elderly"],
    status: "planned",
    placeIds: ["mwsc", "area-29-civic"],
  },

  // ── Scale, timing & governance ───────────────────────────────────────────
  {
    id: "scale-cedd",
    sourceId: "cedd-ktnfln",
    heading: "Scale and phasing of the NDA",
    headingZh: "新發展區規模及分期",
    text: "The KTN/FLN NDA covers 320 ha, implemented in a First Phase (73 ha) and Remaining Phase (247 ha). The first private housing development was completed at the end of 2022 and the first batch of public housing will be ready for population intake in 2026. Upon full development it will provide about 86,200 housing units (about 57,500 public), an additional population of about 227,000 and about 53,000 jobs. A government office complex is also planned in Kwu Tung North.",
    textZh: "古洞北／粉嶺北新發展區佔地320公頃，分第一階段（73公頃）及餘下階段（247公頃）推展。首個私營房屋項目於2022年底落成，首批公營房屋將於2026年入伙。全面發展後將提供約86,200個住宅單位（約57,500個公營）、新增人口約227,000及約53,000個就業機會。古洞北亦計劃興建政府辦公大樓。",
    topics: ["housing", "employment", "governance"],
    status: "under_construction",
    placeIds: ["area-19-housing"],
    timeline: "2026 first public housing intake",
  },
  {
    id: "population-odp",
    sourceId: "pland-odp",
    heading: "Planned population figure in the ODP",
    headingZh: "大綱圖的規劃人口",
    text: "The draft ODP estimates the total planned population of the Kwu Tung North area at about 119,700 upon full development, and states that first intake of population is expected to commence in 2025/26. Other project documents give different figures (for example about 131,600 additional population in the earlier study-stage description), so population estimates should be read as indicative.",
    textZh: "草圖估計古洞北區全面發展後的規劃人口約119,700人，首批人口預計於2025/26年遷入。其他項目文件數字有所不同（例如較早研究階段描述為新增約131,600人），因此人口估算僅供參考。",
    topics: ["housing", "governance"],
    status: "planned",
    placeIds: [],
  },
  {
    id: "nm-bill",
    sourceId: "isd-nm-bill",
    heading: "Northern Metropolis Development Bill",
    headingZh: "《北部都會區發展條例草案》",
    text: "The Government gazetted the Northern Metropolis Development Bill on 3 July 2026 to further streamline planning and lands procedures, expedite construction works and facilitate industry operation. A public consultation ran from 24 March to 22 May 2026. The Government aims to achieve passage of the Bill within this year.",
    textZh: "政府於2026年7月3日刊憲《北部都會區發展條例草案》，以進一步精簡規劃及土地程序、加快工程及便利產業營運。公眾諮詢於2026年3月24日至5月22日進行，政府目標於年內通過草案。",
    topics: ["governance"],
    status: "proposed",
    placeIds: [],
  },
  {
    id: "past-views",
    sourceId: "tpb-9128",
    heading: "What residents asked for during earlier engagement",
    headingZh: "早前公眾參與中居民的訴求",
    text: "During the planning study's public engagement, some members of the public wanted a new hospital to relieve North District Hospital, while others wanted halls, libraries and community elderly homes, and asked for timely provision of facilities to avoid problems seen in Tin Shui Wai New Town. The NDAs were also planned to include integrated children and youth service centres, integrated family service centres, district and neighbourhood elderly centres and residential care homes for the elderly.",
    textZh: "規劃研究的公眾參與期間，部分市民希望興建新醫院以紓緩北區醫院壓力，亦有人希望設會堂、圖書館及社區安老院，並要求適時提供設施，避免重蹈天水圍新市鎮的問題。新發展區亦規劃設綜合青少年服務中心、綜合家庭服務中心、長者地區及鄰舍中心，以及安老院舍。",
    topics: ["community", "elderly", "healthcare", "governance"],
    status: "planned",
    placeIds: [],
  },
];

export const CHUNK_BY_ID = new Map(CHUNKS.map((c) => [c.id, c]));
